FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --no-dev --frozen --no-install-project

COPY api ./api

EXPOSE 8080

CMD [".venv/bin/uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080"]
