FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/app/.venv/bin:${PATH}"

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --no-dev --extra gcp --frozen --no-install-project

COPY cloud ./cloud
COPY data_generator ./data_generator
COPY dbt_neobank ./dbt_neobank
COPY src ./src

CMD ["python", "-m", "src.cloud.jobs.activation_score_load"]
